name: 'Setup League Client' 
description: 'Installs the latest version of the League of Legends client (LCU).'
author: 'Mikael Dúi Bolinder'
branding:
  icon: 'trending-up'  
  color: 'yellow'
inputs:
  username:
    description: 'The username of a League of Legends account.'
    required: true
    type: string
  password:
    description: 'The password for the League of Legends account.'
    required: true
    type: string
  region:
    description: 'The region of the League of Legends account, e.g. "NA".'
    required: true
    type: string
  patchline:
    description: 'League of Legends patchline.'
    required: false
    default: 'live'
    type: string
  config:
    description: 'Config name. Most of the time is the same as region.'
    required: false
    default: ''
    type: string
  full-install:
    description: 'Wait untill full game installation?'
    required: false
    default: true
    type: boolean
  install-pengu:
    description: 'Install Pengu loader?'
    required: false
    default: false
    type: boolean
  is-debug:
    description: 'Print debug information?'
    required: false
    default: false
    type: boolean
outputs:
  rcs-password:
    description: "The Riot Client Session Password. It's NOT your account password."
    value: ${{ steps.install.outputs.rcs-password }}
  rcs-port:
    description: 'The Riot Client Port. Used for communicating with it using HTTPS/WSS.'
    value: ${{ steps.install.outputs.rcs-port }}
  rcs-directory:
    description: 'The Riot Client Installation Directory.'
    value: ${{ steps.install.outputs.rcs-directory }}
  lcu-password:
    description: "The League Client Session Password. It's NOT your account password."
    value: ${{ steps.install.outputs.lcu-password }}
  lcu-port:
    description: 'The League Client Port. Used for communicating with it using HTTPS/WSS.'
    value: ${{ steps.install.outputs.lcu-port }}
  lcu-directory:
    description: 'The League Client Installation Directory.'
    value: ${{ steps.install.outputs.lcu-directory }}
  pengu-directory:
    description: 'Pengu Loader installation directory.'
    value: ${{ steps.install.outputs.pengu-directory }}

runs:
  using: "composite"
  steps:  
    - name: "Ensure it's running on Windows"
      if: ${{ runner.os != 'Windows' }}
      uses: actions/github-script@v6
      with:
        script: core.setFailed('This action must be run on Windows!')
    - name: Restore dependencies
      shell: cmd
      run: dotnet restore src/setup-league-client.csproj
    - name: Setup League of Legends
      id: install
      shell: cmd
      run: dotnet run src/setup-league-client.csproj
      env: # github what the fuck
        INPUT_USERNAME: ${{ inputs.username }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_REGION: ${{ inputs.region }}
        INPUT_PATCHLINE: ${{ inputs.patchline }}
        INPUT_CONFIG: ${{ inputs.config }}
        INPUT_FULL-INSTALL: ${{ inputs.full-install }}
        INPUT_INSTALL-PENGU: ${{ inputs.install-pengu }}
        INPUT_IS-DEBUG: ${{ inputs.is-debug }}
