name: Test
on: workflow_dispatch
concurrency: lol
jobs:
  install:
    name: Test the action
    runs-on: windows-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v3
      - name: Setup the League Client
        id: league-client
        uses: ./
        with:
          username: ${{ secrets.LOL_USERNAME }}
          password: ${{ secrets.LOL_PASSWORD }}
          region: ${{ secrets.LOL_REGION }}
          is-debug: true

      - name: Test outputs
        uses: actions/github-script@v6
        with:
          script: |
            "${{ steps.league-client.outputs.rcs-password }}".length === 0 && core.setFailed("No RCS Password Output");
            "${{ steps.league-client.outputs.rcs-port }}".length === 0 && core.setFailed("No RCS Port Output");
            "${{ steps.league-client.outputs.rcs-directory }}".length === 0 && core.setFailed("No RCS Directory Output");
            "${{ steps.league-client.outputs.lcu-password }}".length === 0 && core.setFailed("No LCU Password Output");
            "${{ steps.league-client.outputs.lcu-port }}".length === 0 && core.setFailed("No LCU Port Output");
            "${{ steps.league-client.outputs.lcu-directory }}".length === 0 && core.setFailed("No LCU Directory Output");
